language: node_js

services: docker

before_install:
  - docker pull ethereum/solc:nightly

script:
  - docker run --rm -v"$TRAVIS_BUILD_DIR:/root/code" ethereum/solc:nightly --hashes /root/code/javabutton.sol
  - docker run --rm -v"$TRAVIS_BUILD_DIR:/root/code" ethereum/solc:nightly --hashes /root/code/bookmark.sol
